### ISSUE TITLE
Active codebase/project?

### ISSUE THREAD

**Issue by siemvaessen** [City-of-Helsinki/openahjo#49]
To whom it may concern: is this codebase still in use with the city of Helsinki? We are scanning open source software for municipalities in The Netherlands to assess if we can re-use an existing codebase.

Any feedback would be welcome.

**Comment by jussiarpalahti** [comment]
Yes, it is very much in use :)

Here's a brief english description https://dev.hel.fi/projects/openahjo/
Open API to same https://dev.hel.fi/apis/openahjo/

Data is mostly in finnish, though :/

**Comment by siemvaessen** [comment]
Hi, got delayed :-)

Good to hear. We'd be interested to learn how we can contribute to this repo once we get our bearings set. One major upgrade we would suggest is moving *away* from Tastypie and migrate to Django DRF. But not sure how your team is thinking and what dependency you have.

Can we setup a call somewhere next week for a Meet & Greet? We could then provide our potential usecases and our experience with Django/DRF (& formerly Tastypie) and AGPL licensing.

We will add @VincentVW to the call.

**Comment by juyrjola** [comment]
@siemvaessen We're definitely moving to DRF in the future. This project is the only one still done with Tastypie, but a major rewrite is planned. Drop me an email at firstname.lastname@hel.fi (without umlaut dots) and let's agree on the schedule for the call.
